### ISSUE TITLE
Rich is a dependency

### ISSUE THREAD

**Issue by account-sxf** [argrento/huami-token#13]
Traceback (most recent call last):
  File "huami_token.py", line 11, in <module>
    from rich.console import Console

Error occurs until you run `pip3 install rich` to get rich! Might pay to update the README.md with this.

**Comment by TimelessNL** [comment]
It is already mentioned in the both the [README.md](https://github.com/argrento/huami-token#dependencies) and [requirements.txt](https://github.com/argrento/huami-token/blob/master/requirements.txt). To me that seems sufficient?
