### ISSUE TITLE
Login Error 0106 - Mi

### ISSUE THREAD

**Issue by severus-tux** [argrento/huami-token#14]
Hi, I am getting the following error after pasting the url

```
Logging in...
Traceback (most recent call last):
  File "huami_token.py", line 252, in <module>
    device.login()
  File "huami_token.py", line 108, in login
    raise ValueError(f"Login error. Error: {login_result['error_code']}")
ValueError: Login error. Error: 0106

```

**Comment by argrento** [comment]
Hi! 

Please take a look in issue #10.

**Comment by severus-tux** [comment]
> Hi!
> 
> Please take a look at issue #10.

Sorry, I couldn't find that closed issue earlier. I checked it now. It didn't help. My Mi band 4 is paired with the MiFit app. It is working fine (showing heart rate etc.. on my phone). With the same account, when I try to run the script (on linux), it gives this error

**Comment by argrento** [comment]
Try this workaround:

1. Download Zepp app (formerly Amazfit)
2. Login there with our Mi cridentials.
3. Pair and sync your band with Zepp app.
4. Try to log in with this script.
5. Error should gone now.

**Comment by severus-tux** [comment]
> Try this workaround:
> 
> 1. Download Zepp app (formerly Amazfit)
> 2. Login there with our Mi cridentials.
> 3. Pair and sync your band with Zepp app.
> 4. Try to log in with this script.
> 5. Error should gone now.


Thanks!. This workaround solves the issue. Pairing with Zepp and running 
```
python huami_token.py --method amazfit --email youemail@example.com --password your_password --bt_keys
```

Gives the Auth Key.

**Comment by argrento** [comment]
Great!
