### ISSUE TITLE
Regarding acquiring auth key for Mi Band 4/5

### ISSUE THREAD

**Issue by maxakash** [argrento/huami-token#15]
Apps like Notify and Fitness, Master for Mi Band doesn't need user credentials to acquire auth key when Mi Fit app is installed.

They somehow acquire the auth key from Mi Fit app. I couldn't find how they do it.

Please help me regarding this matter and  I am even willing to pay for your help.

Thanks

**Comment by argrento** [comment]
I am 90% sure they don't.

**Comment by maxakash** [comment]
> I am 90% sure they don't. 

Yes they do. I have checked my self.

If Mi Fit is installed, they directly connect to Mi Band 4/5.

**Comment by argrento** [comment]
How did you check the fact that Notify and Fitness, Master for Mi Band have access to BT auth key?

**Comment by maxakash** [comment]
There is no other way to connect to Mi Band 4/5 .
So if these apps are accessing band data, they need to have access to auth
key.
