### ISSUE TITLE
amazfit vs. mi fit  

### ISSUE THREAD

**Issue by mishpochology** [argrento/huami-token#2]
Hello 
I have a mi band 4 and use the 'MI FIT' app with a huami account.
When I run your script I come to a page that says:
Sign in to **Amazfit** with Mi Account
When I try to use my huami account it does not recognize me.

Do I need to download the amazfit app and register with this the mi band?

Best regards

**Comment by argrento** [comment]
Probably, yes.
Also you could try to download Amazfit app, login with your cridentials there, sync band with app and then use this script.

**Comment by pierrefabarius** [comment]
> Hello
> I have a mi band 4 and use the 'MI FIT' app with a huami account.
> When I run your script I come to a page that says:
> Sign in to **Amazfit** with Mi Account
> When I try to use my huami account it does not recognize me.
> 
> Do I need to download the amazfit app and register with this the mi band?
> 
> Best regards

I've had the same problem with a Amazfit Lite.
A few days ago I created a new account via the website. After confirming the activation mail I was not able to log in either on the website nor with the MiFit App.
Today I tried again and it worked.
