### ISSUE TITLE
Amazfit account : SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Thomas3971** [argrento/huami-token#20]
Hi,

the script could not be executed successfully.
I am double checked the dependencies in the readme.md, but I could not found any errors.

```
File "huami_token.py", line 42
    print(f"Getting access token with {self.method} login method...")
                                                                   ^
SyntaxError: invalid syntax
```

Model: Amazfit Bip S
System: openSuse Tumbleweed.

Any ideas?

Thanks!
Thomas

**Comment by argrento** [comment]
Hi!

Which version has your python? Please check with `python --version` or `python3 --version`.

**Comment by Thomas3971** [comment]
Hi @argrento ,

thanks for the quick response.

I am found the issue already.

It was necessary to type python3 instead of python to run the script.

> python3 huami_token.py --method amazfit --email youremail@example.com --password password --bt_keys

Installed python versions are:

- 3.8.5
- 2.7.18

Operating System: openSuse Tumbleweed
