### ISSUE TITLE
Mi band 5, problem with retreiving account info

### ISSUE THREAD

**Issue by PooyaJln** [argrento/huami-token#22]
Hi,
I'm trying to get the the auth_key for Mi Band 5 but after pasting the url after the security warning I get a python error although it returns the Token

```
Token: ['ALSG_CLOUDSRV_693DA83C7C743F209EACB663********'] ( I removed part of the token for security reasons)
Logging in...
Traceback (most recent call last):
  File "huami_token.py", line 265, in <module>
    device.login()
  File "huami_token.py", line 116, in login
    raise ValueError(f"Login error. Error: {login_result['error_code']}")
ValueError: Login error. Error: 0117
```

I checked the code itself. I'm not sure but is it using the correct url?

**Comment by argrento** [comment]
Hello! 

You need to download Zepp (former Amazfit) app first and login there with your Mi account. After this trick script will work fine.

**Comment by argrento** [comment]
Does the issue still persist?

**Comment by PooyaJln** [comment]
After using the zepp app, I still had the problem with the second method. I tried the first method (email and password) which worked perfectly.

**Comment by argrento** [comment]
Great!
