### ISSUE TITLE
I can't find my mi4 device that's connected on my mi fit app

### ISSUE THREAD

**Issue by enzoampil** [argrento/huami-token#4]
Are there extra steps I have to take for me to see my mi4 as a device using `python huami_token.py --method xiaomi`?

Output below:

```
Getting linked wearables...





Downloading AGPS_ALM...
Downloading AGPSZIP...
```

**Comment by argrento** [comment]
Try download Amazfit app and login with your cridentials there first. If you see your devices in Amazfit app, you can use script to get tokens.

**Comment by enzoampil** [comment]
I've done the above but still see same blank output above

**Comment by argrento** [comment]
Do you have an ability to sync your device with Amazfit app? Also you should delete or stop Mi Fit app, becuase it can cause pairing conflicts.

**Comment by argrento** [comment]
Hi! Any updates?

**Comment by enzoampil** [comment]
Unfortunately, none of the above worked but I appreciate your help!
