### ISSUE TITLE
UnicodeEncodeError when displaying table

### ISSUE THREAD

**Issue by jezzaaa** [argrento/huami-token#5]
Managed to get to the last stage, but got this error:

```
...
Logging in...
Logged in! User id: <id>
Getting linked wearables...
Traceback (most recent call last):
  File "huami_token.py", line 227, in <module>
    console.print(table)
  File "/opt/lib/python3.6/site-packages/rich/console.py", line 849, in print
    render(renderable, render_options), self.get_style(style)
  File "/opt/lib/python3.6/site-packages/rich/console.py", line 442, in __exit__
    self._exit_buffer()
  File "/opt/lib/python3.6/site-packages/rich/console.py", line 420, in _exit_buffer
    self._check_buffer()
  File "/opt/lib/python3.6/site-packages/rich/console.py", line 957, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-59: ordinal not in range(128)
```

As a work-around, what I ended up doing was simply adding ```print(device_keys)``` just before ```for device_key in device_keys:``` and it showed the auth key right before the above traceback. I used the key to connect GadgetBridge to my Miband 4, no problems.

The output didn't seem to have anything weird in it - just the MAC address and hex auth code. So I don't know why console.py couldn't encode the characters. Maybe it was the table border characters?

**Comment by willmcgugan** [comment]
Hi.

That error is probably caused by the box characters in the table, which are not in the ascii range.

For some reason, console.file has an encoding of ascii. I've seen this occur in Github Actions, setting the env var `PYTHONIOENCODING="utf-8"` usually fixes it.

Another fix would be to set `box=box.ASCII` on the Table class.
