### ISSUE TITLE
no mac or auth_key analyzed

### ISSUE THREAD

**Issue by chzhoudy** [argrento/huami-token#51]
https://hm.xiaomi.com/watch.do?code=C3_003023863265D3316E355FFA16B4867B
Token: ['C3_003023863265D3316E355FFA16B4867B']
Logging in...
Logged in! User id: 1112235618
Getting linked wearables...
+------------------------------------------------------------------------------+
| ID  | ACT |        MAC        |                   auth_key                   |
|-----+-----+-------------------+----------------------------------------------|
+------------------------------------------------------------------------------+

Logged out.

**Comment by argrento** [comment]
Hi! How do you execute `huami_token.py`?

**Comment by JamwongH** [comment]
I have the same problem..

**Comment by JamwongH** [comment]
I've solved this problem by replacing Xiaomi Wear Lite with Mi Fit.

**Comment by chzhoudy** [comment]
bingo
