### ISSUE TITLE
Lack of ability to login to amazfit account via google

### ISSUE THREAD

**Issue by gbdlin** [argrento/huami-token#7]
I've created my Amazfit account using google oauth and now I cannot access it using this tool. Trying to reset the password of my account does not work as this account has no email assigned to it and I cannot find a way to assign one.

Is there any other way I can use this account with this tool? Maybe somebody know a method to set user and password on Amazfit accounts created by oauth?

**Comment by argrento** [comment]
Hi! Thank you for your question. 
Straightforward workaround:

1. Deregister your wearable from current account in Amazfit App.
2. Create new temporary account with login and password.
3. Pair your device with new account.
4. Use this script with amazfit login method to obtain auth key

**Comment by gbdlin** [comment]
Will I be able to connect watch with my normal account again without auth key being changed?

**Comment by argrento** [comment]
No, it seems that a device can be paired with only one account at a time. Sorry :(
