### ISSUE TITLE
Returned Auth Key has invalid character

### ISSUE THREAD

**Issue by snowsquizy** [argrento/huami-token#8]
I have followed the steps in the instructions however the return auth key is:
0xc7908bb8-3c93-4b93-b31a-d25bdaa3f…
The last digit is three periods as a single character (Ellipsis)

**Comment by argrento** [comment]
Hi!
Which device do you have?
Where do you run this script?

It's all strange, because I've never seen dashes in the auth key.

**Comment by snowsquizy** [comment]
I Have an Amazfit Bip A1608 Firmware V1.1.6.34
In a home Folder directory under Debian 10 and python 3.7
It is 30 characters long without the dashes and if the last character is three separate characters it is the right length.

**Comment by argrento** [comment]
In file huami_token.py before line 253 `table.add_row(device_key, device_keys[device_key])` add on the same ident level this line : 
`print(device_key, device_keys[device_key])`

**Comment by snowsquizy** [comment]
It changed the output to 0xc7908bb8-3c93-4b93-b31a-d25bdaa3fff7
Going to go try that as Auth Key and will advise

**Comment by snowsquizy** [comment]
That worked a treat, Thanks for your prompt response
